import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next App",
  keywords: ["Next.js", "React", "Demo"],
  authors: [
    {
      name: "Nikhil Saji",
      url: "https://yourwebsite.com",
    },
  ],
  creator: "Nikhil Saji",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-gray-950`}
      >
        <div className="flex flex-col min-h-screen bg-gray-100 dark:bg-gray-900">
          <main className="flex-grow">{children}
          <Analytics />
          </main>
          <footer className="bg-gray-800 text-white p-1 text-center">
            © 2025 Nikhil Saji
          </footer>
        </div>
      </body>
    </html>
  );
}
